package com.myspace.institut;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Accompagnants")
public class Accompagnants implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "ACCOMPAGNANTS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ACCOMPAGNANTS_ID_SEQ", name = "ACCOMPAGNANTS_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;

	@org.kie.api.definition.type.Label("lastName")
	private java.lang.String lastName;

	public Accompagnants() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public Accompagnants(java.lang.Long id, java.lang.String firstName,
			java.lang.String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

}